---
title: Response to reviewers
author: JCGS-19-044
output:
  MonashEBSTemplates::memo:
    includes:
      in_header: preamble2.tex
fontfamily: mathpazo
---

We thank the reviewers for their helpful feedback which has led to many improvements in the paper. The point by point description of changes are below: the reviewers' comments are in red and our response is in black.

This manuscript has undergone an overhaul to address reviewer's comments:

1. Section 2.2 (previously 2.3) has been extended to include reviews of other software than R (Stata and SAS) time series and longitudinal data standards.
2. We have rewritten Section 3 "Contextual semantics" to give a definition of tsibble in relation to tidy data, and we expand on the four rules of a tsibble in details.
3. We have rewritten Section 4 "Temporal data pipelines" to describe a big picture about each module with the focus of temporal data instead of time series before. We have added Section 4.4 to summarise what a fluent pipeline looks like for a tsibble.
4. We have removed the mosaic plot along with the paragraph from Section 6.1, and added the forecasting example to the smart meter data in Section 6.2 to show tsibble's capability.

Along with these major changes, we have done lots of minor tweaks to improve the manuscript.

# Reviewer 1 comments {-}

> More mini examples embeded throughout the manuscript. Mainly it didn't showcase to me tsibble's capability well enough but understandably this may make the manuscript long and may be better left to vignettes.

Thanks for this comment. We have decided to mostly leave these to the vignettes, which are readily available on the web page for the package. The reason for doing this is that we feel that having many mini examples interrupts the flow of the paper. We have made two additions, though, which hopefully address these comments.

A new code snippet (featuring new `pedestrian` dataset) is added to subsection 4.4. This is new part added to the paper, summarising the transformation and modeling parts of the data pipeline section. A new example is added that showcases how tsibble provides a platform to forecasting. We also include an energy consumption case study in Section 6.2, illustrating the cleaner, and more expressive, temporal data modeling pipeline.

> Finding a duplicate is a nice touch but I don't understand the significance of the Figure 5 mosaic plot in demonstration for the capability of tsibble. I understand that finding duplicate/wrong entry is made easier by tsibble but besides filtering those duplicate/wrong entries, the data wrangling for mosaic plot is easily done without tsibble. More specifically what is the significance `tsibble::index_by` below? Could the authors explain what is the benefit of explicit defining index at this stage as opposed to explicit specification at a later stage?

We have removed the mosaic plot and the paragraph. The `tsibble::index_by()` helps to update the index and interval when used with `summarise()`. It's a useful adverb to have for intuitive temporal manipulation. But you're right it can happen at a later stage.

> In relation to the above point, perhaps it would be helpful to have a definition of tidy temporal data much like the three rules in tidy data (every row is an observation etc..). E.g. in tsibble the semantics index is a variable with some inherent ordering from past to present.

Thanks for this great suggestion. We've given a definition of "tsibble" following the "tidy data" principles in the beginning of Section 3.

> I hold a similar sentiment regarding the calendar plot in Figure 12. It's a great plot but I don't necessary think this is a plot that show cased the benefit of tsibble.

Yes, the calendar plot just requires a data frame. We've added the forecasting example to back up this plot: how the weather information improves the demand forecasts.

> Figure 11 with missing data was a great demonstration for tsibble and the data times series pipeline shown in Figure 3. It may be helpful to reduce the opacity of the points as there is a lot of overplotting. The top line which lumps a number of customers together is not particularly informative here. Perhaps it is better replaced with a histogram.

Thanks. We separated the remaining customers to the bottom panel with points of some transparency. We have kept the line range plot instead of a histogram. Because the range plot is more informative: individual missings are congregated in January and February with sporadic continuous missings over the rest of the year.

> Authors may like to add/change `spread`/`gather` verbs to `pivot_longer`/`pivot_wider` with the recent move to deprecate the former in tidyr. Likewise authors may like to consider to replace “long data” to “longer data” and “wide data” to “wider data” as long/wide implies absolute terms. <https://tidyr.tidyverse.org/dev/articles/pivot.html>

We'd like to upgrade `spread`/`gather` verbs to `pivot_longer`/`pivot_wider`. But they are not S3 generics yet, which delays the implementation. Conceptually the newly melted columns will be added to the key specification.

> Manuscript does implicitly feel more time series data oriented rather than a general temporal data. E.g. references of time points as index seems inherent from other time series data infrastructure (i.e. zoo and xts) and the presented case studies is not representative of any longitudinal study. This does not mean it should be changed but index to me was not as intuitive to be the temporal variable.

Time indexes lay the contextual foundation to both time series and longitudinal data. `zoo` and `xts` store indices as metadata due the matrix structure, but tsibble's indices are explicitly a data column that can be manipulated. The index may be a date-time variable, as is usual in time series, but could be as simple as an ordered integer as is common in longitudinal data. It is also customizable to any variable that can be ordered. We have made this clearer in Section 3.1 where index specification is explained.

Tsibble is aimed at general temporal data, to unify **data** structures underlying time series and longitudinal problems. In Section 4 of the revised manuscript, we clarify the different focuses of time series and longitudinal **analysis** and modelling. However, we have kept the emphasis on time series for the examples, because there are more functions available for time series model building on tsibble.

> Figure 4 animation doesn't play so authors may like to ensure that the final publication works. Github version works.

Thanks for pointing it out. We include a gif version of the animation as supplementary materials.

> Have the authors thought about how to deal with mixed time resolutions for index? E.g. some subjects have exact day recorded; some missing day but month & year recorded; some only date range recorded.

We have rewritten Section 3.3 to better explain intervals and address the mixed time resolutions.

> The emphasis of the manuscripts is in R but do other languages also tend to define time index implicitly?

We have rewritten Section 2.2 (previously 2.3) to review a broader range of existing data structures in R, Stata, and SAS.

Thanks for the careful reading. We have done with minor comments.

# Reviewer 2 comments {-}

> P5L37 "Temporal data tools need to catch up." This is a little casual. Could perhaps be rephrased as "This paper and the associated **tsibble** R package extends the tidy way of thinking to temporal data."

Done.

> P7L44 "A variable number of time representations can be spotted in the wild." This is a little casual, and I’m not fond of "variable number". Perhaps "Many different representations of temporal data can be spotted in the wild." (The "spotted in the wild" is still a little informal – but I like it.)

Done.

> P7L50 "This diversity and time zone..." suggest rephrase "The tsibble's index column leverages the date-time data type in R to accommodate diverse temporal representations and associated time zone information."

We removed that sentence.

> P8L16 "The identifying variables from which the "key" is constituted remain the same as in the original table with no further tweaks." It's not totally clear to me what is meant here. Is it saying that like with grouping columns (i.e. columns supplied to group_by()), key columns cannot be altered in subsequent analyses? It might be useful to make the comparison to group_by() explicit as it also allows multiple fields. The distinction between group_by() and key() is clear in that the collection of columns that constitute a key must uniquely identify observations (obviously this isn’t the case for grouping variables).

We have re-written Section 3.2 about "key" to be clearer on defining observational units. `group_by()` is a transient operation and not limited to certain variables, but "key" persistently identifies observational units. But "key" can be altered when the observational units are changed during the course of transformation.

> P8L55 "fit models that expect **regular** time series." Should regular be added to the sentence.

Done.

> P10L19 "Duplicates signal a data quality..."

Done.

> P12-13 Consider referencing "fable: and possibly "mable" too.

We added the reference to the **fable** package, and removed the mention of mable in Section 4.3.

> P14-15 I had to read section 5.2 a few times before I understood it... I think what threw me was the last paragraph starts with a reference to purrr, but the functions described in the remainder of the paragraph describes functions in the tsibble package. Perhaps move the purrr sentence up to the previous paragraph when functional programming is first mentioned.

Done. We moved **purrr** to the opening sentence of the previous paragraph.

> P15L46 "...table verb achieves in collapsing a tsibble..." perhaps "...table verb collapse a tsibble..."

Done.

> P15L53 "On the other hand, these tsibble verbs can incorporate many third-party vector functions to step out of the current tsibble zone" perhaps "The extensible design of the tsibble package means that the table verbs can incorporate many third-party vector functions."

Done.

> Fig 5 y-axis doesn't need the overall label "Delayed" or if it stays, should be renamed “Status”. Similarly for the legend label.

We removed the mosaic plot (previously Figure 5).

> Fig 6 Consider replacing gather() with pivot_longer() which is intended to be easier to use particularly for more complex "gathering" operations. <https://tidyr.tidyverse.org/dev/articles/pivot.html>

We'd like to upgrade `spread`/`gather` verbs to `pivot_longer`/`pivot_wider`. But they are not S3 generics yet, which delays the implementation. Conceptually the newly melted columns will be added to the key specification.


> Fig 7 y-axis label should be "Proportion of flights delayed" or similar. Legend label "Originating airport" (but legend can also be removed, because it is covered by the facet labels.

Done.

> Fig 9 y-label "Departure delay (mins)". X-axis could be converted to time... e.g. ggplot2::scale_x_time() Could introduce some alpha transparency to the geom_line(). Caption text currently states "Passengers are apt to hold up around 18 during a day, and are recommended to travel early. The variations increase substantially as the upper tails." Both sentences need to be reworded.

Done.

> P22L3 "might be joined" should it be "can be joined" or perhaps a bit more detail, "Aggregating the half-hourly electricity data to the same daily time interval as the temperature data allows us to join the two data tables to explore..."

Thanks. Done.

> P22L27 Suggest a reference to Wang, E, D Cook & RJ Hyndman (2018) to explicitly acknowledge that the frame_calendar() function is part of a different package (sugrrants).

Done.

> P22L37 "degrees C" to "degrees Celsius" or °C

Done.

> Fig 12 remove legend label "hot"

Done.

> P25L19 It's not "A missing piece of the tsibble package" because later in the paragraph it says that custom calendars are easily embedded in the tsibble framework. I suggest rephrasing the first sentence in a more positive light... "The tsibble package can easily be extended to accommodate user-defined calendars." Suggest also referencing at least one package that provides a user-defined calendar (perhaps a market-specific business calendar).

We have re-written the custom calendars part, the last paragraph of Section 7. Conceptually it's easy to embed custom calendars into the tsibble framework, but a general flexible calendar software system is lacking, which delays the implementation. We added the **bizdays** R package as reference.

> P26L54 there's an errant

Fixed.

> P28L22 Journal of Statistical Software

Fixed.
